name: Update version badge

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Extract version from manifest
        id: get_version
        run: |
          VERSION=$(jq -r '.version' manifest.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create badge JSON
        run: |
          cat <<EOF > badge.json
          {
            "schemaVersion": 1,
            "label": "Extension",
            "message": "v${VERSION}",
            "color": "blue"
          }
          EOF

      - name: Commit badge.json
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add badge.json
          git commit -m "Update badge to version v${VERSION}" || echo "No changes"
          git push || echo "No changes to push"
